In [1]:
import numpy as np

In [ ]:
# 1
x = np.arange(10,50,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# 2
y = np.zeros((4,6))
print(y)
y[2, :] = 99
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


In [ ]:
# 3
arr =np.array([12,45,7,19,88,3,56,91,24,67])
print(arr[arr>50])

[88 56 91 67]


In [ ]:
# 4
x = np.eye(5)
print(x)
np.fill_diagonal(x, [10,20,30,40,50])
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


In [ ]:
# 5
x =np.arange(1,21).reshape(4,5)
print(x)
print('------------')
print(x[-2:])
print('------------')
print(x[:, 2:3])
print('------------')
print(x[:3, 2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------
[[11 12 13 14 15]
 [16 17 18 19 20]]
------------
[[ 3]
 [ 8]
 [13]
 [18]]
------------
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [ ]:
# 6
a = np.array([1,2,3,4,5])
b = np.array([[10], [20], [30]])
print(a)
print(b)
print('---------')
print(a+b)

# b stretched to be 3*5: same y dimension as a
# it became:
# [10,10,10,10,10]
# [20,20,20,20,20]
# [30,30,30,30,30]
# then added to a elements



[1 2 3 4 5]
[[10]
 [20]
 [30]]
---------
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]


In [ ]:
# 7
data = np.array([150,220,90,300,180,45])

data_norm = (data - data.min()) / (data.max() - data.min())

print(data)
print(data_norm)

[150 220  90 300 180  45]
[0.41176471 0.68627451 0.17647059 1.         0.52941176 0.        ]


In [ ]:
# 8
data = np.array([150,220,90,300,180,45])

data_std = (data - data.mean()) / data.std()

print(data)
print(data_std)

[150 220  90 300 180  45]
[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


In [ ]:
# 9
mat = np.array([
    [4,8,1,12],
    [7,3,9,5],
    [11,2,6,10],
    [15,0,14,13]
])

print(mat.mean(axis=1))
print(mat.sum(axis=1))

print('Max: ', mat.max())

row, col = np.unravel_index(mat.argmax(), mat.shape)
print('Max Position: ', row, col)

[ 6.25  6.    7.25 10.5 ]
[25 24 29 42]
Max:  15
Max Position:  3 0


In [ ]:
# 10
x = np.arange(36)
print(x)

print(x.reshape(3,4,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [ ]:
# 11
arr = np.arange(1, 17).reshape(4,4)
print(arr)
print('----------')
print(np.flip(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
# 12
ages = np.array([23,45,19,34,28,51,17,39])
names = np.array(['Ali', 'Sara', 'Omar', 'Lina', 'Khaled', 'Nour', 'Yara', 'Hassan'])

mask = (ages >= 25) & (ages <= 40)

print(names[mask])

['Lina' 'Khaled' 'Hassan']


In [ ]:
# 13
ages = np.array([23,45,19,34,28,51,17,39])
names = np.array(['Ali', 'Sara', 'Omar', 'Lina', 'Khaled', 'Nour', 'Yara', 'Hassan'])

ages[ages < 20] = 20
print(ages)

[23 45 20 34 28 51 20 39]


In [ ]:
# 14
np.random.seed(123)

arr = np.random.randint(1,101,size=(6,6))

print(arr)

[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [ ]:
# 15
np.random.seed(123)

arr = np.random.normal(loc=100, scale=15, size=10)
print(arr)

[ 83.71554095 114.9601817  104.24467747  77.40557929  91.32099622
 124.77154806  63.59981135  93.56631057 118.98904388  86.99889397]


In [ ]:
# 16
colors = ["red", "blue", "green", "yellow", "purple"]

x = np.random.choice(colors, size=3, replace=False)
print(x)

['purple' 'blue' 'red']


In [ ]:
# 17
nums = np.arange(1,21)
np.random.shuffle(nums)
print(nums)

[14  4  1  7 13 15 16 17  9  5  3 10 18  6 11 19  2 20 12  8]
